Squashed commit of the following:
commit 113078bf5ccbcc1a7205bed00ef4535addbf10a9
Author: jingkaimori <jingkaimori@gmail.com>
Date:   Fri Sep 1 21:14:42 2023 +0800

    fix number parser

commit dc7f84dec66e2bf3dcf987a1ca0ff76c55e2699f
Author: jingkaimori <jingkaimori@gmail.com>
Date:   Fri Sep 1 21:14:29 2023 +0800

    fix logger error

commit 2146fc4dd1f02c44a9ae1b7fc5c954d369d2d401
Author: jingkaimori <jingkaimori@gmail.com>
Date:   Fri Sep 1 00:15:23 2023 +0800

    Added support for unicode

commit 4fe1809ce792c616bc35b2bc489a6a02be9dccd3
Author: Yiheng Wu <36156959+jingkaimori@users.noreply.github.com>
Date:   Tue Aug 22 22:50:51 2023 +0800

    improve xmake build and fix msvc bugs (#31)

commit ab6578dd0d2de51a6fb6d512160d6b07674eedf1
Author: PikachuHy <pikachuhy@163.com>
Date:   Sun Aug 20 20:54:34 2023 +0800

    [doc] update pscm-build document

commit ad8d2fc9f1bf5077d701b5ccfe6189b76e46c27c
Author: PikachuHy <pikachuhy@163.com>
Date:   Sun Aug 20 17:57:00 2023 +0800

    [pscm-build] support c++20 modules

commit 7b5c56102a8b3d4faedcfb546ae68e6a704b45a1
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 22 01:02:25 2023 +0800

    [CXX20Modules] use C++20 Modules

commit 05315d16a166983e5deea9251cb2f751cd7f8636
Author: PikachuHy <pikachuhy@163.com>
Date:   Mon Jul 17 00:35:43 2023 +0800

    add pscm logger

commit a077c53f51f96c1cf8409a7f4382a5db7102ff71
Author: PikachuHy <pikachuhy@163.com>
Date:   Fri Jul 21 22:21:02 2023 +0800

    [ci] disable Windows CI

    FIXME: error C2010: '.': unexpected in macro parameter list

commit 24544136043a46744d0e905d5a2ed1c749fcd8ab
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 15 23:09:35 2023 +0800

    [bazel] build all targets with c++20

commit 0a191447068306d2fd7acb39191675e9e7a3dfa3
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 15 18:53:27 2023 +0800

    [ci] use pscm.wasm built by bazel

commit 37519ec5b9e32a05eab4c14346a734430a1f39a3
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 15 16:54:02 2023 +0800

    [ci] upload artifact

    - android apk
    - ios ipa
    - wasm

commit 6ea76f3bf7ada42750849074ab1fc6ba87ec484b
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 15 16:19:46 2023 +0800

    use new generated VersionInfo

    note: the new VersionInfo is compatible with both CMake and Bazel

    thanks to https://github.com/JulianSchmid/example-bazel-add-git-hash

commit 7f2c0f541de3e54601410b0dd68f9830a84d88a2
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 15 16:17:37 2023 +0800

    [ci] disable xmake ci due to new generated VersionInfo

commit 2a64df22843452fb57dc817d8518cc1cb8b117a7
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 15 15:58:57 2023 +0800

    [ci] disable Linux WASM

    after fix node: bad option: --experimental-wasm-bulk-memory
    the ci can be restored

commit 134202ea131c663e2c96481a0d1955d3add3b485
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jul 15 11:56:28 2023 +0800

    [bazel] build wasm with bazel

commit ab5afb91597bed56dc06d92d0bce8943f0dedaaa
Author: PikachuHy <pikachuhy@163.com>
Date:   Tue Jul 11 00:31:30 2023 +0800

    [bazel] add test

commit 5a22022b46a59e44b4c0191149117e6118a5736a
Author: PikachuHy <pikachuhy@163.com>
Date:   Tue Jul 11 00:30:57 2023 +0800

    [doc] update code statistics for v0.3.0

commit c592ef26ad6a20c666270dbc5ff2b5e38bdc67ba
Author: PikachuHy <pikachuhy@163.com>
Date:   Mon Jun 26 23:24:57 2023 +0800

    bump version v0.3.0

commit 603c1483680b986d0ef9dd31f90e24ad79734db0
Author: PikachuHy <pikachuhy@163.com>
Date:   Fri Jun 23 00:33:13 2023 +0800

    [no ci] update README: add vau pdf preview link

commit d45a50974ab9c88aec2ff0acf558fc01453d0fae
Author: PikachuHy <pikachuhy@163.com>
Date:   Thu Jun 22 23:02:14 2023 +0800

    [ci] add vau ci

commit e2916a67ed09378685a4e6b7dabaaa3571648933
Author: PikachuHy <pikachuhy@163.com>
Date:   Thu Jun 22 23:33:34 2023 +0800

    [vau] support vau phase 5

    run vau success

commit 5a385d681ff82674f8c6b7cc4d7e5bc9e033b9eb
Author: PikachuHy <pikachuhy@163.com>
Date:   Thu Jun 22 20:47:06 2023 +0800

    [test] ignore number_test on macOS

commit ee8b2ac34fd32ccea286b8f7a9cdf21276ae8e5d
Author: PikachuHy <pikachuhy@163.com>
Date:   Thu Jun 22 19:28:58 2023 +0800

    [compat] c++14 compat

commit 211385b36800612d7e11113f298afb02b06bcace
Author: PikachuHy <pikachuhy@163.com>
Date:   Sun Jun 18 19:27:23 2023 +0800

    [vau] support vau phase 4

commit 3c565441e5cf9c4fcd0b6d292ca5762da15cf3c2
Author: PikachuHy <pikachuhy@163.com>
Date:   Sun Jun 18 09:49:59 2023 +0800

    [feature] support repl

commit ed2518c4d23c991186a728d40a18a7d77d14acf0
Author: PikachuHy <pikachuhy@163.com>
Date:   Sun Jun 18 01:03:45 2023 +0800

    [3rd] add cpp-linenoise

commit b1b53a3bce0f4a70f888c2501f3e572f7e11550e
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jun 17 23:52:27 2023 +0800

    [no ci] update README

commit 470bc36835231c4e3c9e6a1c6978c36a26785cc6
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jun 17 23:02:28 2023 +0800

    [ci] use ccache

commit 1072296c870cb8bf8ee4c0f6165bd9e7c510131d
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jun 17 22:40:44 2023 +0800

    [ios] add pscm ios demo

commit 3bf733c6df8576d8f9b20056f556c3bf825f3ef9
Author: PikachuHy <pikachuhy@163.com>
Date:   Sat Jun 17 13:22:31 2023 +0800

    [android] add pscm android demo

commit 00da09553bb0658c284c9079d43178295831259c
Author: PikachuHy <pikachuhy@163.com>
Date:   Tue May 30 23:05:44 2023 +0800

    [vau] support vau phase 3

    full module system support
    support alist
    support hash-table
    add backtrace to exception

commit 5c5005326dddd83451ba195317c1ab2671b7871c
Author: PikachuHy <pikachuhy@163.com>
Date:   Tue May 30 00:54:30 2023 +0800

    [vau] support vau phase 2

    partial module system support
    add macro PSCM_DEFINE_BUILTIN_MACRO
    add macro PSCM_DEFINE_BUILTIN_MACRO_PROC_WRAPPER

commit b7b2502b615475af83e39fc6d02ca8efd2df9c88
Author: PikachuHy <pikachuhy@163.com>
Date:   Sun May 21 10:03:33 2023 +0800

    [vau] support vau phase 1

    add ApiManager
    keyword support
    fake module support
    fake hash-table support

commit 4ed03436054268201a7a5f96815e5661661e7685
Author: PikachuHy <pikachuhy@163.com>
Date:   Mon May 15 21:55:13 2023 +0800

    [feature] support macro